const produitss = 
[ 
    {magasin:"nejah",produits:[
        {nom:''},
        {nom:'Baguettes',prix: 100},
        {nom:'Croissant Pain Chocolat',prix: 100},
        {nom:'croissant Lunettes',prix: 100},
        {nom:'Carre',prix: 100},
        {nom:'Mini croissant',prix: 100},
        {nom:'Cake',prix: 100},
        {nom:'Baklawa',prix: 100},
        {nom:'Cigar',prix: 100},
        {nom:'Harissa',prix: 100},
        {nom:'Cereales',prix: 100},
        {nom:'Kamh',prix: 100},
        {nom:'Panini',prix: 100},
        {nom:'Mlewi',prix: 100},
        {nom:'Gateaux',prix: 100},
        {nom:'Mille Feuilles',prix: 100},
        {nom:'Delice',prix: 100},
        {nom: 'Brioche',prix: 100},
        {nom:'Boules',prix: 100},
        {nom: 'Louzia',prix: 100},
        {nom: 'Croquant',prix: 100},
        {nom: 'Macaron',prix: 100},
        {nom: 'Louzia_speciale',prix: 100},]
    },

    {magasin:"amin",produits:[
        {nom:''},
        {nom:'Baguettes',prix: 100},
        {nom:'Smid',prix: 100},
        {nom:'Smid double',prix: 100},
        {nom:'Zitoun',prix: 100},
        {nom:'Croissant Pain Chocolat',prix: 100},
        {nom:'croissant Lunettes',prix: 100},
        {nom:'Carre',prix: 100},
        {nom:'Mini croissant',prix: 100},
        {nom:'Mabsout',prix: 100},
        {nom:'Baklawa',prix: 100},
        {nom:'Cigar',prix: 100},
        {nom:'Harissa',prix: 100},
        {nom:'Cereales',prix: 100},
        {nom:'Kamh',prix: 100},
        {nom:'Panini',prix: 100},
        {nom:'Mlewi',prix: 100},
        {nom:'Gateaux',prix: 100},
        {nom:'Mille Feuilles',prix: 100},
        {nom:'Delice',prix: 100},
        {nom: 'Brioche',prix: 100},
        {nom:'Boules',prix: 100},
        {nom: 'Louzia',prix: 100},
        {nom: 'Croquant',prix: 100},
        {nom: 'Macaron',prix: 100},
        {nom: 'Louzia_speciale',prix: 100},]
    },

    {magasin:"tiss",produits:[
        {nom:''},
        {nom:'Baguettes',prix: 100},
        {nom:'Baguettes Smid',prix: 100},
        {nom:'Zitoun',prix: 100},
        {nom:'Smid',prix: 100},
        {nom:'Smid double',prix: 100},
        {nom:'Croissant Pain Chocolat',prix: 100},
        {nom:'croissant Lunettes',prix: 100},
        {nom:'Carre',prix: 100},
        {nom:'Mini croissant',prix: 100},
        {nom:'Cake',prix: 100},
        {nom:'Mabsout',prix: 100},
        {nom:'Baklawa',prix: 100},
        {nom:'Cigar',prix: 100},
        {nom:'Harissa',prix: 100},
        {nom:'Cereales',prix: 100},
        {nom:'Kamh',prix: 100},
        {nom:'Panini',prix: 100},
        {nom:'Mlewi',prix: 100},
        {nom:'Gateaux',prix: 100},
        {nom:'Mille Feuilles',prix: 100},
        {nom:'Delice',prix: 100},
        {nom: 'Brioche',prix: 100},
        {nom:'Boules',prix: 100},
        {nom: 'Louzia',prix: 100},
        {nom: 'Croquant',prix: 100},
        {nom: 'Macaron',prix: 100},
        {nom: 'Libanaise',prix: 100},
        {nom: 'Louzia_speciale',prix: 100},]
    },

    {magasin:"jalel",produits:[
        {nom:''},
        {nom:'Baguettes',prix: 100},
        {nom:'Croissant Pain Chocolat',prix: 100},
        {nom:'croissant Lunettes',prix: 100},
        {nom:'Carre',prix: 100},
        {nom:'Mini croissant',prix: 100},
        {nom:'Baklawa',prix: 100},
        {nom:'Cigar',prix: 100},
        {nom:'Harissa',prix: 100},
        {nom:'Cereales',prix: 100},
        {nom:'Kamh',prix: 100},
        {nom:'Panini',prix: 100},
        {nom:'Mlewi',prix: 100},
        {nom:'Gateaux',prix: 100},
        {nom:'Mille Feuilles',prix: 100},
        {nom:'Delice',prix: 100},
        {nom: 'Brioche',prix: 100},
        {nom:'Boules',prix: 100},
        {nom: 'Louzia',prix: 100},
        {nom: 'Croquant',prix: 100},
        {nom: 'Macaron',prix: 100},
        {nom: 'Louzia_speciale',prix: 100},]
    },
];

export default produitss;
